/**
 * lib/db/buero.ts — Büro-Domain-Barrel
 * Re-exportiert alle Büro-Funktionen aus lib/db.ts.
 */
export {
  getBueroKunden,
  getBueroKundeById,
  upsertBueroKunde,
  deleteBueroKunde,
  checkBueroKundeDuplicate,
  anonymisiereBueroKunde,
  getBueroAngebote,
  upsertBueroAngebot,
  getBueroAngebotById,
  getBueroAuftraege,
  upsertBueroAuftrag,
  getBueroAuftragById,
  getBueroRechnungen,
  upsertBueroRechnung,
  getBueroRechnungById,
  getLatestBueroRechnungBySubscriptionId,
  deleteBueroAngebot,
  deleteBueroAuftrag,
  deleteBueroRechnung,
  getBueroEingangsrechnungen,
  upsertBueroEingangsrechnung,
  getBueroEingangsrechnungById,
  deleteBueroEingangsrechnung,
  markEingangsrechnungBezahlt,
  updateEingangsrechnungStatus,
  getBueroDokumente,
  insertBueroDokument,
  updateBueroDokument,
  deleteBueroDokument,
  uploadDokument,
  getDokumentUrl,
  getBueroDokumentById,
  getBueroKundeDetailContext,
  getBueroAngebotDetailContext,
  getBueroAuftragDetailContext,
  archiveRechnungPdf,
  archiveAngebotPdf,
  getArchivPdfSignedUrl,
  getNextInvoiceNumber,
  getNextAngebotNumber,
} from '../db'
